/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package geometric.init;

public class App {

    public static void main(String[] args) {
        System.out.println("Factory App Assigment...");
    }
}
